import:
  - ~/.config/alacritty/dracula.yml
env:
  WINIT_X11_SCALE_FACTOR: "1.0"
window:
  opacity: 0.98
font:
  normal:
    family: MesloLGM Nerd Font Mono
key_bindings:
  - { key: Return,   mods: Shift,   chars: "\x1b[13;2u" }
  - { key: Return,   mods: Control, chars: "\x1b[13;5u" }
  - { key: Return,   mods: Super|Shift, action: SpawnNewInstance }
